<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SelectDataset.aspx.cs" Inherits="DataMiningApp.SelectDataset" %>
<%@ Register assembly="System.Web.DataVisualization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI.DataVisualization.Charting" tagprefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        #File1
        {
            width: 276px;
        }
        </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
    <p>
        Select a dataset</p>
    <asp:DropDownList ID="DatasetList" runat="server" AutoPostBack="False" 
        Width="421px" oninit="DatasetList_Init">
    </asp:DropDownList>
    <br />
    <br />
    <br />
    <p>
        Upload a dataset...</p>
    <p>
        &nbsp;<asp:FileUpload ID="DataSetUpload" runat="server" 
        style="text-align: left;" oninit="DataSetUpload_Init" Width="318px" />
    </p>
    &nbsp;<asp:Button ID="Preview" runat="server" 
        onclick="Preview_Click" Text="Preview" />
    <br />
    <asp:Button ID="UploadAs" runat="server" Text="Upload As..." 
        onclick="UploadAs_Click" />
    <asp:TextBox ID="DataSetName" runat="server" Width="449px"></asp:TextBox>
    <br />
    <hr style="text-align: right" />
    <br />
    <asp:Button ID="Next" runat="server" Height="27px" style="text-align: left" 
        Text="Next" onclick="Next_Click" />
    <asp:Button ID="doPCA" runat="server" onclick="doPCA_Click" Text="Go PCA" />
    <hr />
    <br />
    Dataset preview<br />
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateSelectButton="True" onrowdeleting="GridView1_RowDeleting" 
        >
    </asp:GridView>
    <br />
    </asp:Content>
